services:
  app:
    build: ./server
    container_name: tic-tac-toe-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tictactoeapp
      - JWT_SECRET=jwt-secret-key
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./server:/app
  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tictactoeapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  client:
    build: ./client
    container_name: tic-tac-toe-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - app
volumes:
  postgres-data:
