### GET /

GET http://localhost:5000/

### Register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "ts",
    "password": "ts"
}

### Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "ts",
    "password": "ts"
}

###Fetch
GET http://localhost:5000/game
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1NjI5NzIwLCJleHAiOjE3NTU3MTYxMjB9.cVl1kgz-XrgAePQO28kYBFm-wOktP-GAjyp34IfsY28

### Create
POST http://localhost:5000/game
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1NDQ5OTc1LCJleHAiOjE3NTU1MzYzNzV9.6wlKb6LaHO9ZGRjyTkbps2e4DKO564bKzgdfwYVQgos
Content-Type: application/json

{
    "board":["", "", "", "", "", "", "", "", ""],
    "player": "X",
    "turn": "X",
    "game_result": "In progress",
    "game_ended": 0
}

### Update
PUT http://localhost:5000/game/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU1NjI4OTkyLCJleHAiOjE3NTU3MTUzOTJ9.fGEW0Zmhgv4gEus8KC5CMsyO2Iu-yI8QqHGvg1qOI7I

{
    "board":["X", "", "", "", "", "", "", "", ""],
    "player": "X",
    "turn": "X",
    "game_result": "X won",
    "game_ended": 0
}